#!/usr/bin/env python3
"""Pre-build gate: validates selection-report.json was generated by the real scorer."""

from __future__ import annotations

import argparse
from pathlib import Path

from _common import load_json, now_iso, write_json, SYSTEM_ROOT


VALID_ACTIONS = {"reuse", "adapt-local", "custom-local", "blocked"}
REQUIRED_CRITERIA = {"semantic_intent", "content_structure", "density", "brand", "export_compatibility", "accessibility"}

# Adapt-local floor — kept in sync with score_visual_items.py decision branch.
ADAPT_FLOOR = 65

# T1 selection-lock: each content_shape maps to the intent/tag tokens a chosen
# component must carry. Matched (lowercased) against the registry item's
# intent + tags. Synonyms are included so the map is lenient on phrasing but
# strict on category (a `timeline` shape can never lock to a `cover` item).
SHAPE_TYPE_MAP: dict[str, set[str]] = {
    "cover": {"cover", "hero", "title", "opening", "intro"},
    "stats": {"statistics", "data", "metrics", "kpi", "numbers", "figures", "grid"},
    "comparison": {"comparison", "versus", "do-dont", "what-how", "pros-cons", "contrast"},
    "timeline": {"timeline", "schedule", "roadmap", "process", "milestones", "phases", "instructions"},
    "checklist": {"checklist", "preparation", "steps", "action-items", "todo", "requirements"},
    "two-column": {"two-column", "split", "split-layout", "layout"},
}


def _chk(name: str, ok: bool, detail: str) -> dict:
    return {"name": name, "pass": ok, "detail": detail}


def _registry_tokens(registry: dict) -> dict[str, set[str]]:
    """Map item_id -> lowercased set of intent + tags from the registry."""
    index: dict[str, set[str]] = {}
    for item in registry.get("items", []):
        tokens = {str(t).lower() for t in (item.get("intent", []) + item.get("tags", []))}
        index[item.get("id")] = tokens
    return index


def _content_shapes(vreqs) -> dict[str, str | None]:
    """Map request_id -> content_shape from visual-requests.json (batch or single)."""
    shapes: dict[str, str | None] = {}
    if isinstance(vreqs, list):
        pool = vreqs
    elif isinstance(vreqs, dict):
        pool = vreqs.get("slides") or vreqs.get("requests") or [vreqs]
    else:
        pool = []
    for entry in pool:
        if isinstance(entry, dict) and entry.get("request_id"):
            shapes[entry["request_id"]] = entry.get("content_shape")
    return shapes


def _validate_shape_lock(rep: dict, is_batch: bool, shapes: dict, reg_tokens: dict,
                         strict_shape: bool) -> tuple[list[str], list[str]]:
    """T1: a reuse/adapt-local item's intent/tags must match the slide's content_shape."""
    errs: list[str] = []
    warns: list[str] = []
    if is_batch:
        decisions = [(s.get("request_id"), s.get("decision") or {})
                     for s in rep.get("slides", []) if isinstance(s, dict)]
    else:
        decisions = [(rep.get("request_id"), rep.get("decision") or {})]
    for rid, dec in decisions:
        action = dec.get("action", "")
        item_id = dec.get("item_id")
        if action not in ("reuse", "adapt-local") or not item_id:
            continue
        shape = shapes.get(rid)
        if not shape:
            msg = f"slide {rid!r}: missing content_shape (required for T1 selection-lock)"
            (errs if strict_shape else warns).append(msg)
            continue
        if shape not in SHAPE_TYPE_MAP:
            errs.append(f"slide {rid!r}: unknown content_shape {shape!r} "
                        f"(allowed: {', '.join(sorted(SHAPE_TYPE_MAP))})")
            continue
        allowed = SHAPE_TYPE_MAP[shape]
        tokens = reg_tokens.get(item_id, set())
        if not (allowed & tokens):
            errs.append(
                f"slide {rid!r}: content_shape {shape!r} requires one of {sorted(allowed)}, "
                f"but chosen item {item_id!r} has intent/tags {sorted(tokens) or '[]'}"
            )
    return errs, warns


def _validate_slide_entry(slide: dict, idx: int, errors: list[str], warnings: list[str]) -> list[dict]:
    checks: list[dict] = []
    prefix = f"slides[{idx}]"
    dec = slide.get("decision") or {}
    missing_dec = {"action", "item_id", "score", "reason"} - set(dec)
    action = dec.get("action", "")
    action_ok = action in VALID_ACTIONS
    if missing_dec or not action_ok:
        errors.append(f"{prefix} decision: missing={sorted(missing_dec)}, action={action!r}")
    cands = slide.get("candidates")
    if not isinstance(cands, list) or not cands:
        errors.append(f"{prefix}: missing or empty candidates")
        return checks
    for j, cand in enumerate(cands):
        if not isinstance(cand, dict):
            continue
        crit = cand.get("criteria") or {}
        miss = REQUIRED_CRITERIA - set(crit)
        if miss:
            errors.append(f"{prefix}.candidates[{j}] criteria missing: {', '.join(sorted(miss))}")
            break
    item_id = dec.get("item_id")
    if action in ("reuse", "adapt-local") and not item_id:
        errors.append(f"{prefix}: action={action!r} but item_id is null")
    score_val = dec.get("score", 0)
    if isinstance(score_val, (int, float)) and score_val >= 75 and action != "reuse":
        warnings.append(f"{prefix}: score {score_val} >= 75 but action is {action!r}")
    if isinstance(score_val, (int, float)) and 0 < score_val < ADAPT_FLOOR and action in ("reuse", "adapt-local"):
        warnings.append(f"{prefix}: score {score_val} < {ADAPT_FLOOR} but action is {action!r} (below adapt-local floor)")
    return checks


def _validate_batch(rep: dict, checks: list[dict], errors: list[str], warnings: list[str], fail) -> None:
    missing = {"generated_at", "slides"} - set(rep)
    ok = not missing
    checks.append(_chk("schema", ok, "Batch schema valid" if ok else f"Missing: {', '.join(sorted(missing))}"))
    if not ok:
        fail(f"Batch schema missing: {', '.join(sorted(missing))}")

    slides = rep.get("slides", [])
    if not isinstance(slides, list) or not slides:
        fail("Batch report has no slides")
        checks.append(_chk("slides_array", False, "Missing or empty slides array"))
        return
    checks.append(_chk("slides_array", True, f"{len(slides)} slide(s)"))

    slide_errors: list[str] = []
    slide_warnings: list[str] = []
    for i, slide in enumerate(slides):
        if not isinstance(slide, dict):
            slide_errors.append(f"slides[{i}] is not an object")
            continue
        if "request_id" not in slide:
            slide_errors.append(f"slides[{i}] missing request_id")
        _validate_slide_entry(slide, i, slide_errors, slide_warnings)

    ok = not slide_errors
    checks.append(_chk("slide_entries", ok, f"All {len(slides)} entries valid" if ok else f"{len(slide_errors)} error(s)"))
    if not ok:
        for e in slide_errors:
            fail(e)
    warnings.extend(slide_warnings)


def _validate_single(rep: dict, checks: list[dict], errors: list[str], warnings: list[str], fail) -> None:
    missing = {"request_id", "generated_at", "decision", "candidates"} - set(rep)
    ok = not missing
    checks.append(_chk("schema", ok, "All top-level keys present" if ok else f"Missing: {', '.join(sorted(missing))}"))
    if not ok:
        fail(f"Schema missing top-level keys: {', '.join(sorted(missing))}")

    dec = rep.get("decision") or {}
    missing_dec = {"action", "item_id", "score", "reason"} - set(dec)
    action = dec.get("action", "")
    action_ok = action in VALID_ACTIONS
    ok = not missing_dec and action_ok
    detail = "Decision schema valid" if ok else "; ".join(
        ([f"missing: {', '.join(sorted(missing_dec))}"] if missing_dec else [])
        + ([f"invalid action: {action!r}"] if not action_ok else [])
    )
    checks.append(_chk("decision_schema", ok, detail))
    if not ok:
        fail(f"Decision: {detail}")

    cands = rep.get("candidates")
    ok = isinstance(cands, list) and len(cands) > 0
    checks.append(_chk("candidates_array", ok, f"{len(cands)} candidate(s)" if ok else "Missing or empty candidates array"))
    if not ok:
        fail("Candidates: missing or empty array")
        cands = []

    crit_errors: list[str] = []
    for i, cand in enumerate(cands):
        if not isinstance(cand, dict):
            crit_errors.append(f"Candidate[{i}] is not an object")
            continue
        for key in ("item_id", "eligible", "score", "criteria"):
            if key not in cand:
                crit_errors.append(f"Candidate[{i}] missing '{key}'")
        crit = cand.get("criteria") or {}
        miss = REQUIRED_CRITERIA - set(crit)
        if miss:
            crit_errors.append(f"Candidate[{i}] criteria missing: {', '.join(sorted(miss))}")
    ok = not crit_errors
    checks.append(_chk("criteria_sub_scores", ok, "All criteria keys present" if ok else "; ".join(crit_errors[:3])))
    if not ok:
        errors.extend(crit_errors)

    # Equal scores across candidates are legitimate (two items can be equally
    # relevant, or all blocked items score 0.0). The only implausible case is
    # eligible items that all scored zero.
    scores = [c.get("score") for c in cands if isinstance(c, dict) and "score" in c]
    eligible_any = any(c.get("eligible") for c in cands if isinstance(c, dict))
    all_zero = bool(scores) and all(s == 0 for s in scores)
    plaus_ok = not (eligible_any and all_zero)
    detail = "Scores are plausible" if plaus_ok else "All scores are 0 despite eligible items"
    checks.append(_chk("score_plausibility", plaus_ok, detail))
    if not plaus_ok:
        fail(detail)

    item_id = dec.get("item_id")
    score_val = dec.get("score", 0)
    adopt_ok = not (action in ("reuse", "adapt-local") and not item_id)
    checks.append(_chk("adoption_compliance", adopt_ok,
        "Adoption rules satisfied" if adopt_ok else f"action={action!r} but item_id is null"))
    if not adopt_ok:
        fail(f"Adoption: action={action!r} requires non-null item_id")
    if isinstance(score_val, (int, float)) and score_val >= 75 and action != "reuse":
        warnings.append(f"Score {score_val} >= 75 but action is {action!r}, expected 'reuse'")
    if isinstance(score_val, (int, float)) and 0 < score_val < ADAPT_FLOOR and action in ("reuse", "adapt-local"):
        warnings.append(f"Score {score_val} < {ADAPT_FLOOR} but action is {action!r} (below adapt-local floor)")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--selection-report", required=True)
    parser.add_argument("--visual-requests", default=None,
                        help="visual-requests.json — required to run the T1 content_shape lock.")
    parser.add_argument("--registry", default=str(SYSTEM_ROOT / "registries/visual-library.json"),
                        help="Full registry (default). Must carry intent/tags for shape-lock.")
    parser.add_argument("--strict-shape", action="store_true",
                        help="Promote a missing content_shape from WARN to a hard FAIL (T1 rollout).")
    args = parser.parse_args()

    report_path = Path(args.selection_report).resolve()
    rep = load_json(report_path)
    checks: list[dict] = []
    errors: list[str] = []
    warnings: list[str] = []

    def fail(msg: str) -> None:
        errors.append(msg)

    is_batch = "slides" in rep and isinstance(rep.get("slides"), list)

    if is_batch:
        _validate_batch(rep, checks, errors, warnings, fail)
    else:
        _validate_single(rep, checks, errors, warnings, fail)

    # Provenance (HARD — both modes). The scorer always stamps generated_by;
    # a report that lacks it or carries any other value was not produced by the
    # scorer and is rejected. This is what backs the "NO hand-written selection
    # reports" prohibition — it must be an error, not a warning.
    generated_by = rep.get("generated_by")
    prov_ok = generated_by == "score_visual_items.py"
    checks.append(_chk("provenance", prov_ok,
        "generated_by is score_visual_items.py" if prov_ok else f"generated_by is {generated_by!r}, expected 'score_visual_items.py'"))
    if not prov_ok:
        fail(f"generated_by is {generated_by!r}, expected 'score_visual_items.py' (report not produced by the scorer)")

    # T1 selection-lock: chosen component's intent/tags must match content_shape.
    # Needs both the registry (for the item's tokens) and visual-requests (for
    # the per-slide content_shape).
    if args.visual_requests:
        try:
            reg_tokens = _registry_tokens(load_json(args.registry))
            shapes = _content_shapes(load_json(args.visual_requests))
            s_errs, s_warns = _validate_shape_lock(rep, is_batch, shapes, reg_tokens, args.strict_shape)
            ok = not s_errs
            checks.append(_chk("shape_lock", ok,
                "content_shape <-> component type consistent" if ok else f"{len(s_errs)} shape mismatch(es)"))
            errors.extend(s_errs)
            warnings.extend(s_warns)
        except Exception as exc:
            warnings.append(f"shape-lock skipped: {exc}")

    # Cross-check with visual-requests (optional)
    if args.visual_requests:
        vreqs = load_json(args.visual_requests)
        if is_batch:
            vreq_ids = {s.get("request_id") for s in vreqs.get("slides", []) if isinstance(s, dict)}
            rep_ids = {s.get("request_id") for s in rep.get("slides", []) if isinstance(s, dict)}
            missing_ids = vreq_ids - rep_ids
            ok = not missing_ids
            checks.append(_chk("request_id_match", ok,
                f"All {len(rep_ids)} request IDs matched" if ok else f"Missing: {', '.join(sorted(missing_ids))}"))
            if not ok:
                fail(f"Cross-check: {len(missing_ids)} request ID(s) from visual-requests not scored")
        else:
            rid = rep.get("request_id")
            req_ids = {r.get("request_id") for r in (vreqs if isinstance(vreqs, list) else vreqs.get("requests", vreqs.get("slides", []))) if isinstance(r, dict)}
            ok = rid in req_ids
            checks.append(_chk("request_id_match", ok,
                f"request_id {rid!r} found" if ok else f"request_id {rid!r} not in visual-requests"))
            if not ok:
                fail(f"Cross-check: request_id {rid!r} not found in visual-requests")

    valid = not errors
    result = {"valid": valid, "checked_at": now_iso(), "report_path": str(report_path),
              "checks": checks, "errors": errors, "warnings": warnings}
    write_json(report_path.parent.parent / "analysis" / "selection-validation.json", result)

    status = "PASS" if valid else "FAIL"
    print(f"validate_selection_report: {status}{f' ({len(warnings)} warning(s))' if warnings else ''} — {report_path.name}")
    for e in errors:
        print(f"  ERROR: {e}")
    for w in warnings:
        print(f"  WARN: {w}")
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
