#!/usr/bin/env python3
"""Pre-build gate: validates selection-report.json was generated by the real scorer."""

from __future__ import annotations

import argparse
from pathlib import Path

from _common import load_json, now_iso, write_json, SYSTEM_ROOT
from component_units import unit_model
from score_visual_items import SHAPE_TYPE_MAP, declared_set_sizes, shape_lock_ok
from validate_slot_content_plan import _contracts_from_registry


VALID_ACTIONS = {"reuse", "text-only"}
REQUIRED_CRITERIA = {"semantic_intent", "content_structure", "density", "brand", "export_compatibility", "accessibility"}
DECISION_FIELDS = {"action", "item_id", "score", "reason", "extraction_recommended", "warnings", "evidence"}
SINGLE_REPORT_FIELDS = {
    "request_id", "generated_at", "generated_by", "scorer_version",
    "retrieval_index", "rejected_items", "decision", "candidates",
}
BATCH_REPORT_FIELDS = {
    "job_id", "generated_at", "generated_by", "scorer_version",
    "retrieval_index", "rejected_items", "slides",
}
SLIDE_FIELDS = {"request_id", "decision", "candidates"}

def _chk(name: str, ok: bool, detail: str) -> dict:
    return {"name": name, "pass": ok, "detail": detail}


def _validate_report_fields(rep: dict, is_batch: bool, errors: list[str]) -> dict:
    """Reject agent-authored curation fields in the scorer-owned artifact."""
    allowed_report = BATCH_REPORT_FIELDS if is_batch else SINGLE_REPORT_FIELDS
    unexpected_report = set(rep) - allowed_report
    if unexpected_report:
        errors.append(
            "selection report contains non-scorer field(s): "
            + ", ".join(sorted(unexpected_report))
        )

    entries = rep.get("slides", []) if is_batch else [rep]
    for index, entry in enumerate(entries):
        prefix = f"slides[{index}]" if is_batch else "report"
        if not isinstance(entry, dict):
            continue
        unexpected_slide = set(entry) - SLIDE_FIELDS if is_batch else set()
        if unexpected_slide:
            errors.append(
                f"{prefix} contains non-scorer field(s): "
                + ", ".join(sorted(unexpected_slide))
            )
        decision = entry.get("decision") or {}
        if isinstance(decision, dict):
            unexpected_decision = set(decision) - DECISION_FIELDS
            if unexpected_decision:
                errors.append(
                    f"{prefix}.decision contains non-scorer field(s): "
                    + ", ".join(sorted(unexpected_decision))
                )
    return _chk("scorer_owned_fields", not unexpected_report and not errors,
                "Only scorer-owned fields present" if not unexpected_report and not errors
                else "Found non-scorer fields")


def _validate_decision_action(slide: dict, prefix: str, errors: list[str]) -> None:
    """Enforce the scorer-owned published-only decision contract.

    A published, buildable candidate is reused directly. Otherwise generation
    is text-only; it never creates a local visual structure.
    """
    decision = slide.get("decision") or {}
    if not isinstance(decision, dict):
        return
    action = decision.get("action")
    item_id = decision.get("item_id")
    if action == "reuse":
        candidates = [
            candidate for candidate in slide.get("candidates") or []
            if isinstance(candidate, dict)
            and candidate.get("eligible")
            and candidate.get("item_id") == item_id
        ]
        if candidates:
            return
        errors.append(
            f"{prefix}.decision reuse item {item_id!r} is not an eligible scored candidate; "
            "regenerate the report instead of curating it."
        )
    elif action == "text-only":
        if item_id is not None:
            errors.append(f"{prefix}.decision text-only action must have item_id null")
        if decision.get("score") != 0:
            errors.append(f"{prefix}.decision text-only action must have score 0")


def _registry_tokens(registry: dict) -> dict[str, set[str]]:
    """Map item_id -> lowercased set of intent + tags from the registry."""
    index: dict[str, set[str]] = {}
    for item in registry.get("items", []):
        tokens = {str(t).lower() for t in (item.get("intent", []) + item.get("tags", []))}
        index[item.get("id")] = tokens
    return index


def _registry_set_sizes(registry: dict) -> dict[str, set[int]]:
    """Map item_id -> declared `set-of-N` sizes, for the parallel-set allowance."""
    return {item.get("id"): declared_set_sizes(item) for item in registry.get("items", [])}


def _requests_by_id(vreqs) -> dict[str, dict]:
    """Map request_id -> the whole request from visual-requests.json.

    The full request is needed, not just `content_shape`: T1 now also reads the
    declared `repeatable-set-of-N` and `item_count` evidence.
    """
    requests: dict[str, dict] = {}
    if isinstance(vreqs, list):
        pool = vreqs
    elif isinstance(vreqs, dict):
        pool = vreqs.get("slides") or vreqs.get("requests") or [vreqs]
    else:
        pool = []
    for entry in pool:
        if isinstance(entry, dict) and entry.get("request_id"):
            requests[entry["request_id"]] = entry
    return requests


def _validate_shape_lock(rep: dict, is_batch: bool, requests: dict, reg_tokens: dict,
                         strict_shape: bool, reg_sizes: dict | None = None
                         ) -> tuple[list[str], list[str]]:
    """T1: a reused item must match the slide's content_shape.

    Delegates the decision to `score_visual_items.shape_lock_ok` so the scorer
    and this gate cannot drift, including the parallel-set allowance.
    """
    errs: list[str] = []
    warns: list[str] = []
    reg_sizes = reg_sizes or {}
    if is_batch:
        decisions = [(s.get("request_id"), s.get("decision") or {})
                     for s in rep.get("slides", []) if isinstance(s, dict)]
    else:
        decisions = [(rep.get("request_id"), rep.get("decision") or {})]
    for rid, dec in decisions:
        action = dec.get("action", "")
        item_id = dec.get("item_id")
        if action != "reuse" or not item_id:
            continue
        request = requests.get(rid) or {}
        shape = request.get("content_shape")
        if not shape:
            msg = f"slide {rid!r}: missing content_shape (required for T1 selection-lock)"
            (errs if strict_shape else warns).append(msg)
            continue
        if shape not in SHAPE_TYPE_MAP:
            errs.append(f"slide {rid!r}: unknown content_shape {shape!r} "
                        f"(allowed: {', '.join(sorted(SHAPE_TYPE_MAP))})")
            continue
        tokens = reg_tokens.get(item_id, set())
        sizes = reg_sizes.get(item_id, set())
        if not shape_lock_ok(shape, request, tokens, sizes):
            errs.append(
                f"slide {rid!r}: content_shape {shape!r} requires one of "
                f"{sorted(SHAPE_TYPE_MAP[shape])}, but chosen item {item_id!r} has "
                f"intent/tags {sorted(tokens) or '[]'} and declares set sizes "
                f"{sorted(sizes) or '[]'} (no parallel-set match either)"
            )
    return errs, warns


def _item_counts(vreqs) -> dict[str, object]:
    """Map request_id -> item_count from visual-requests.json (batch or single)."""
    counts: dict[str, object] = {}
    if isinstance(vreqs, list):
        pool = vreqs
    elif isinstance(vreqs, dict):
        pool = vreqs.get("slides") or vreqs.get("requests") or [vreqs]
    else:
        pool = []
    for entry in pool:
        if isinstance(entry, dict) and entry.get("request_id"):
            counts[entry["request_id"]] = entry.get("item_count")
    return counts


def _reuse_decisions(rep: dict, is_batch: bool) -> list[tuple[str, dict]]:
    if is_batch:
        pairs = [(s.get("request_id"), s.get("decision") or {})
                 for s in rep.get("slides", []) if isinstance(s, dict)]
    else:
        pairs = [(rep.get("request_id"), rep.get("decision") or {})]
    return [(rid, dec) for rid, dec in pairs
            if dec.get("action") == "reuse" and dec.get("item_id")]


def _validate_unit_model(rep: dict, is_batch: bool, counts: dict,
                         contracts: dict) -> list[str]:
    """T2 visual-unit lock: repeat count must match the requested item count.

    A component that repeats six cards cannot host four parallel ideas without
    shipping two blank cards, and per-slot capacity cannot see that — every
    mapped slot fits. Rejecting here is deterministic and lets the normal
    pipeline fall back to another eligible published component or to text-only,
    instead of inventing a custom-local visual.

    Only the component's own geometry is consulted. A component with no repeat
    structure (a cover, a quote, a closing) declares no unit count; unknown is
    not a mismatch, exactly like the scorer's `set-of-N` rule.
    """
    errs: list[str] = []
    for rid, dec in _reuse_decisions(rep, is_batch):
        item_count = counts.get(rid)
        if not isinstance(item_count, int) or isinstance(item_count, bool) or item_count < 2:
            continue
        contract = contracts.get(str(dec.get("item_id")))
        if not contract:
            continue
        model = unit_model(contract)
        units = model.get("primary_unit_count")
        if not isinstance(units, int) or units == item_count:
            continue
        example = model["primary"]["slot_ids"][0] if model.get("primary") else []
        errs.append(
            f"slide {rid!r}: request needs {item_count} parallel item(s) but chosen component "
            f"{dec.get('item_id')!r} repeats {units} native unit(s) "
            f"(e.g. {', '.join(example) or 'n/a'}); "
            f"{abs(units - item_count)} unit(s) would ship "
            f"{'blank' if units > item_count else 'over-filled'}. "
            "Reselect a published component with "
            f"{item_count} unit(s), or render this slide text-only."
        )
    return errs


def _validate_slide_entry(slide: dict, idx: int, errors: list[str], warnings: list[str]) -> list[dict]:
    checks: list[dict] = []
    prefix = f"slides[{idx}]"
    dec = slide.get("decision") or {}
    missing_dec = {"action", "item_id", "score", "reason", "extraction_recommended"} - set(dec)
    action = dec.get("action", "")
    action_ok = action in VALID_ACTIONS
    if missing_dec or not action_ok:
        errors.append(f"{prefix} decision: missing={sorted(missing_dec)}, action={action!r}")
    cands = slide.get("candidates")
    if not isinstance(cands, list) or not cands:
        errors.append(f"{prefix}: missing or empty candidates")
        return checks
    for j, cand in enumerate(cands):
        if not isinstance(cand, dict):
            continue
        crit = cand.get("criteria") or {}
        miss = REQUIRED_CRITERIA - set(crit)
        if miss:
            errors.append(f"{prefix}.candidates[{j}] criteria missing: {', '.join(sorted(miss))}")
            break
    item_id = dec.get("item_id")
    if action == "reuse" and not item_id:
        errors.append(f"{prefix}: action={action!r} but item_id is null")
    if action == "text-only" and item_id is not None:
        errors.append(f"{prefix}: action='text-only' but item_id is not null")
    # Scorer advisories (weak subject match, unscoreable request terms) are
    # non-blocking, but they must reach the reviewer instead of staying buried
    # in the report the gate summary replaces.
    for note in dec.get("warnings") or []:
        warnings.append(f"{slide.get('request_id', prefix)}: {note}")
    _validate_decision_action(slide, prefix, errors)
    return checks


def _validate_batch(rep: dict, checks: list[dict], errors: list[str], warnings: list[str], fail) -> None:
    missing = {"generated_at", "slides"} - set(rep)
    ok = not missing
    checks.append(_chk("schema", ok, "Batch schema valid" if ok else f"Missing: {', '.join(sorted(missing))}"))
    if not ok:
        fail(f"Batch schema missing: {', '.join(sorted(missing))}")

    slides = rep.get("slides", [])
    if not isinstance(slides, list) or not slides:
        fail("Batch report has no slides")
        checks.append(_chk("slides_array", False, "Missing or empty slides array"))
        return
    checks.append(_chk("slides_array", True, f"{len(slides)} slide(s)"))

    slide_errors: list[str] = []
    slide_warnings: list[str] = []
    for i, slide in enumerate(slides):
        if not isinstance(slide, dict):
            slide_errors.append(f"slides[{i}] is not an object")
            continue
        if "request_id" not in slide:
            slide_errors.append(f"slides[{i}] missing request_id")
        _validate_slide_entry(slide, i, slide_errors, slide_warnings)

    ok = not slide_errors
    checks.append(_chk("slide_entries", ok, f"All {len(slides)} entries valid" if ok else f"{len(slide_errors)} error(s)"))
    if not ok:
        for e in slide_errors:
            fail(e)
    warnings.extend(slide_warnings)


def _validate_single(rep: dict, checks: list[dict], errors: list[str], warnings: list[str], fail) -> None:
    missing = {"request_id", "generated_at", "decision", "candidates"} - set(rep)
    ok = not missing
    checks.append(_chk("schema", ok, "All top-level keys present" if ok else f"Missing: {', '.join(sorted(missing))}"))
    if not ok:
        fail(f"Schema missing top-level keys: {', '.join(sorted(missing))}")

    dec = rep.get("decision") or {}
    missing_dec = {"action", "item_id", "score", "reason", "extraction_recommended"} - set(dec)
    action = dec.get("action", "")
    action_ok = action in VALID_ACTIONS
    ok = not missing_dec and action_ok
    detail = "Decision schema valid" if ok else "; ".join(
        ([f"missing: {', '.join(sorted(missing_dec))}"] if missing_dec else [])
        + ([f"invalid action: {action!r}"] if not action_ok else [])
    )
    checks.append(_chk("decision_schema", ok, detail))
    if not ok:
        fail(f"Decision: {detail}")

    cands = rep.get("candidates")
    ok = isinstance(cands, list) and len(cands) > 0
    checks.append(_chk("candidates_array", ok, f"{len(cands)} candidate(s)" if ok else "Missing or empty candidates array"))
    if not ok:
        fail("Candidates: missing or empty array")
        cands = []

    crit_errors: list[str] = []
    for i, cand in enumerate(cands):
        if not isinstance(cand, dict):
            crit_errors.append(f"Candidate[{i}] is not an object")
            continue
        for key in ("item_id", "eligible", "score", "criteria"):
            if key not in cand:
                crit_errors.append(f"Candidate[{i}] missing '{key}'")
        crit = cand.get("criteria") or {}
        miss = REQUIRED_CRITERIA - set(crit)
        if miss:
            crit_errors.append(f"Candidate[{i}] criteria missing: {', '.join(sorted(miss))}")
    ok = not crit_errors
    checks.append(_chk("criteria_sub_scores", ok, "All criteria keys present" if ok else "; ".join(crit_errors[:3])))
    if not ok:
        errors.extend(crit_errors)

    # Equal scores across candidates are legitimate (two items can be equally
    # relevant, or all candidates can score 0.0). The only implausible case is
    # eligible items that all scored zero.
    scores = [c.get("score") for c in cands if isinstance(c, dict) and "score" in c]
    eligible_any = any(c.get("eligible") for c in cands if isinstance(c, dict))
    all_zero = bool(scores) and all(s == 0 for s in scores)
    plaus_ok = not (eligible_any and all_zero)
    detail = "Scores are plausible" if plaus_ok else "All scores are 0 despite eligible items"
    checks.append(_chk("score_plausibility", plaus_ok, detail))
    if not plaus_ok:
        fail(detail)

    item_id = dec.get("item_id")
    adopt_ok = not ((action == "reuse" and not item_id) or (action == "text-only" and item_id is not None))
    checks.append(_chk("adoption_compliance", adopt_ok,
        "Published-only decision rules satisfied" if adopt_ok else f"action={action!r} has incompatible item_id={item_id!r}"))
    if not adopt_ok:
        fail(f"Adoption: action={action!r} has incompatible item_id={item_id!r}")
    _validate_decision_action(rep, "report", errors)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--selection-report", required=True)
    parser.add_argument("--visual-requests", default=None,
                        help="visual-requests.json — required to run the T1 content_shape lock.")
    parser.add_argument("--registry", default=str(SYSTEM_ROOT / "registries/visual-library.json"),
                        help="Full registry (default). Must carry intent/tags for shape-lock.")
    parser.add_argument("--strict-shape", action="store_true",
                        help="Promote a missing content_shape from WARN to a hard FAIL (T1 rollout).")
    args = parser.parse_args()

    report_path = Path(args.selection_report).resolve()
    rep = load_json(report_path)
    checks: list[dict] = []
    errors: list[str] = []
    warnings: list[str] = []

    def fail(msg: str) -> None:
        errors.append(msg)

    is_batch = "slides" in rep and isinstance(rep.get("slides"), list)

    if is_batch:
        _validate_batch(rep, checks, errors, warnings, fail)
    else:
        _validate_single(rep, checks, errors, warnings, fail)

    checks.append(_validate_report_fields(rep, is_batch, errors))

    # Provenance (HARD — both modes). The scorer always stamps generated_by;
    # a report that lacks it or carries any other value was not produced by the
    # scorer and is rejected. This is what backs the "NO hand-written selection
    # reports" prohibition — it must be an error, not a warning.
    generated_by = rep.get("generated_by")
    prov_ok = generated_by == "score_visual_items.py"
    checks.append(_chk("provenance", prov_ok,
        "generated_by is score_visual_items.py" if prov_ok else f"generated_by is {generated_by!r}, expected 'score_visual_items.py'"))
    if not prov_ok:
        fail(f"generated_by is {generated_by!r}, expected 'score_visual_items.py' (report not produced by the scorer)")

    # T1 selection-lock: chosen component's intent/tags must match content_shape.
    # Needs both the registry (for the item's tokens) and visual-requests (for
    # the per-slide content_shape).
    if args.visual_requests:
        try:
            shape_registry = load_json(args.registry)
            reg_tokens = _registry_tokens(shape_registry)
            reg_sizes = _registry_set_sizes(shape_registry)
            requests = _requests_by_id(load_json(args.visual_requests))
            s_errs, s_warns = _validate_shape_lock(rep, is_batch, requests, reg_tokens,
                                                   args.strict_shape, reg_sizes)
            ok = not s_errs
            checks.append(_chk("shape_lock", ok,
                "content_shape <-> component type consistent" if ok else f"{len(s_errs)} shape mismatch(es)"))
            errors.extend(s_errs)
            warnings.extend(s_warns)
        except Exception as exc:
            warnings.append(f"shape-lock skipped: {exc}")

        # T2 visual-unit lock: the chosen component's repeat structure must be
        # able to host exactly the requested number of parallel items.
        try:
            registry = load_json(args.registry)
            reused = {dec["item_id"] for _, dec in _reuse_decisions(rep, is_batch)}
            contracts = _contracts_from_registry(registry, reused)
            u_errs = _validate_unit_model(rep, is_batch, _item_counts(load_json(args.visual_requests)),
                                          contracts)
            ok = not u_errs
            checks.append(_chk("visual_unit_lock", ok,
                "item_count <-> component repeat structure consistent" if ok
                else f"{len(u_errs)} unit-model mismatch(es)"))
            errors.extend(u_errs)
        except Exception as exc:
            warnings.append(f"visual-unit lock skipped: {exc}")

    # Cross-check with visual-requests (optional)
    if args.visual_requests:
        vreqs = load_json(args.visual_requests)
        if is_batch:
            vreq_ids = {s.get("request_id") for s in vreqs.get("slides", []) if isinstance(s, dict)}
            rep_ids = {s.get("request_id") for s in rep.get("slides", []) if isinstance(s, dict)}
            missing_ids = vreq_ids - rep_ids
            ok = not missing_ids
            checks.append(_chk("request_id_match", ok,
                f"All {len(rep_ids)} request IDs matched" if ok else f"Missing: {', '.join(sorted(missing_ids))}"))
            if not ok:
                fail(f"Cross-check: {len(missing_ids)} request ID(s) from visual-requests not scored")
        else:
            rid = rep.get("request_id")
            req_ids = {r.get("request_id") for r in (vreqs if isinstance(vreqs, list) else vreqs.get("requests", vreqs.get("slides", []))) if isinstance(r, dict)}
            ok = rid in req_ids
            checks.append(_chk("request_id_match", ok,
                f"request_id {rid!r} found" if ok else f"request_id {rid!r} not in visual-requests"))
            if not ok:
                fail(f"Cross-check: request_id {rid!r} not found in visual-requests")

    valid = not errors
    result = {"valid": valid, "checked_at": now_iso(), "report_path": str(report_path),
              "checks": checks, "errors": errors, "warnings": warnings}
    write_json(report_path.parent.parent / "analysis" / "selection-validation.json", result)

    status = "PASS" if valid else "FAIL"
    print(f"validate_selection_report: {status}{f' ({len(warnings)} warning(s))' if warnings else ''} — {report_path.name}")
    for e in errors:
        print(f"  ERROR: {e}")
    for w in warnings:
        print(f"  WARN: {w}")
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
