#!/usr/bin/env python3
"""Pre-build gate: validates selection-report.json was generated by the real scorer."""

from __future__ import annotations

import argparse
from pathlib import Path

from _common import load_json, now_iso, write_json, SYSTEM_ROOT, SHAPE_TYPE_MAP
from score_visual_items import AUTO_REUSE_MIN, SEMANTIC_CONFIDENCE_FRAC, WEIGHTS

# Auto-reuse confidence bar — imported from the scorer so the gate and the scorer
# cannot drift. reuse/needs_component/custom-local is the new product vocabulary;
# `adapt-local` and `blocked` are retired as automatic actions (product decision
# 2026-07-13.20).
SEMANTIC_CONFIDENCE = round(WEIGHTS["semantic_intent"] * SEMANTIC_CONFIDENCE_FRAC, 2)
VALID_ACTIONS = {"reuse", "needs_component", "custom-local", "blank"}
REQUIRED_CRITERIA = {"semantic_intent", "content_structure", "density", "brand", "export_compatibility", "accessibility"}
DECISION_FIELDS = {"action", "item_id", "score", "reason", "extraction_recommended",
                   "suggested_search", "next_action", "selected_by", "allow_component_reuse",
                   "immutable_text_conflict", "capacity_conflict", "shortlist"}
SINGLE_REPORT_FIELDS = {
    "request_id", "generated_at", "generated_by", "scorer_version",
    "retrieval_index", "decision", "candidates",
}
BATCH_REPORT_FIELDS = {
    "job_id", "generated_at", "generated_by", "scorer_version",
    "retrieval_index", "slides",
}
SLIDE_FIELDS = {"request_id", "decision", "candidates"}

SEMANTIC_FLOOR = 10.5

# T1 selection-lock vocabulary now lives in _common.SHAPE_TYPE_MAP so the scorer
# (candidate eligibility) and this validator (defense-in-depth shape-lock) share
# one source of truth and cannot drift. Imported above.


def _chk(name: str, ok: bool, detail: str) -> dict:
    return {"name": name, "pass": ok, "detail": detail}


def _validate_report_fields(rep: dict, is_batch: bool, errors: list[str]) -> dict:
    """Reject agent-authored curation fields in the scorer-owned artifact."""
    allowed_report = BATCH_REPORT_FIELDS if is_batch else SINGLE_REPORT_FIELDS
    unexpected_report = set(rep) - allowed_report
    if unexpected_report:
        errors.append(
            "selection report contains non-scorer field(s): "
            + ", ".join(sorted(unexpected_report))
        )

    entries = rep.get("slides", []) if is_batch else [rep]
    for index, entry in enumerate(entries):
        prefix = f"slides[{index}]" if is_batch else "report"
        if not isinstance(entry, dict):
            continue
        unexpected_slide = set(entry) - SLIDE_FIELDS if is_batch else set()
        if unexpected_slide:
            errors.append(
                f"{prefix} contains non-scorer field(s): "
                + ", ".join(sorted(unexpected_slide))
            )
        decision = entry.get("decision") or {}
        if isinstance(decision, dict):
            unexpected_decision = set(decision) - DECISION_FIELDS
            if unexpected_decision:
                errors.append(
                    f"{prefix}.decision contains non-scorer field(s): "
                    + ", ".join(sorted(unexpected_decision))
                )
    return _chk("scorer_owned_fields", not unexpected_report and not errors,
                "Only scorer-owned fields present" if not unexpected_report and not errors
                else "Found non-scorer fields")


def _validate_decision_band(slide: dict, prefix: str, errors: list[str]) -> None:
    """Enforce the new selection contract against the scored candidates, so a
    post-score rewrite fails closed:
      - custom-local requires explicit user approval (selected_by == 'user');
        the scorer NEVER auto-creates a custom layout.
      - AUTOMATIC reuse must name a candidate that clears the confidence bar
        (total >= AUTO_REUSE_MIN AND semantic >= SEMANTIC_CONFIDENCE) and is
        eligible + shape-compatible.
      - EXPLICIT reuse (selected_by == 'user') bypasses the score bar but is still
        subject to the shape-lock/fidelity gates elsewhere.
      - needs_component carries no band obligation.
    """
    decision = slide.get("decision") or {}
    if not isinstance(decision, dict):
        return
    action = decision.get("action")
    if action == "custom-local":
        if decision.get("selected_by") != "user":
            errors.append(
                f"{prefix}.decision: custom-local requires explicit user approval "
                f"(selected_by='user'); the scorer never auto-creates a custom layout.")
        return
    if action == "blank":
        if decision.get("selected_by") != "user":
            errors.append(
                f"{prefix}.decision: blank requires an explicit user choice "
                f"(selected_by='user'); the scorer never blanks a slide automatically.")
        return
    if action != "reuse":
        return
    if decision.get("selected_by") == "user":
        return  # explicit selection bypasses the auto bar (still fidelity/shape-gated)
    cands = {c.get("item_id"): c for c in slide.get("candidates") or [] if isinstance(c, dict)}
    chosen = cands.get(decision.get("item_id"))
    if not chosen:
        errors.append(f"{prefix}.decision: reuse item_id {decision.get('item_id')!r} is not "
                      f"among the scored candidates.")
        return
    if not chosen.get("eligible") or not chosen.get("shape_eligible", True):
        errors.append(f"{prefix}.decision: automatic reuse of ineligible/shape-incompatible "
                      f"item {decision.get('item_id')!r}.")
    score = chosen.get("score", 0)
    semantic = (chosen.get("criteria") or {}).get("semantic_intent", 0)
    if score < AUTO_REUSE_MIN or semantic < SEMANTIC_CONFIDENCE:
        errors.append(
            f"{prefix}.decision: automatic reuse of {decision.get('item_id')!r} (total {score}, "
            f"semantic {semantic}) is below the confidence bar (>= {AUTO_REUSE_MIN} total AND "
            f">= {SEMANTIC_CONFIDENCE} semantic). Use needs_component or an explicit selection.")


def _registry_tokens(registry: dict) -> dict[str, set[str]]:
    """Map item_id -> lowercased set of intent + tags from the registry."""
    index: dict[str, set[str]] = {}
    for item in registry.get("items", []):
        tokens = {str(t).lower() for t in (item.get("intent", []) + item.get("tags", []))}
        index[item.get("id")] = tokens
    return index


def _content_shapes(vreqs) -> dict[str, str | None]:
    """Map request_id -> content_shape from visual-requests.json (batch or single)."""
    shapes: dict[str, str | None] = {}
    if isinstance(vreqs, list):
        pool = vreqs
    elif isinstance(vreqs, dict):
        pool = vreqs.get("slides") or vreqs.get("requests") or [vreqs]
    else:
        pool = []
    for entry in pool:
        if isinstance(entry, dict) and entry.get("request_id"):
            shapes[entry["request_id"]] = entry.get("content_shape")
    return shapes


def _validate_shape_lock(rep: dict, is_batch: bool, shapes: dict, reg_tokens: dict,
                         strict_shape: bool) -> tuple[list[str], list[str]]:
    """T1: a `reuse` item's intent/tags must match the slide's content_shape."""
    errs: list[str] = []
    warns: list[str] = []
    if is_batch:
        decisions = [(s.get("request_id"), s.get("decision") or {})
                     for s in rep.get("slides", []) if isinstance(s, dict)]
    else:
        decisions = [(rep.get("request_id"), rep.get("decision") or {})]
    for rid, dec in decisions:
        action = dec.get("action", "")
        item_id = dec.get("item_id")
        shape = shapes.get(rid)
        # Under --strict-shape every scored request must declare a content_shape,
        # regardless of its decision, so the slide-generator workflow cannot skip
        # the shape-aware filter by omitting content_shape on a custom-local slide.
        if strict_shape and not shape:
            errs.append(f"slide {rid!r}: content_shape is required under --strict-shape")
            continue
        # ...and it must be a KNOWN shape from the shared vocabulary. Checked
        # before the action/item_id early-return so an unknown content_shape also
        # fails on needs_component/custom-local decisions, not only `reuse`.
        if strict_shape and shape not in SHAPE_TYPE_MAP:
            errs.append(f"slide {rid!r}: unknown content_shape {shape!r} under --strict-shape "
                        f"(allowed: {', '.join(sorted(SHAPE_TYPE_MAP))})")
            continue
        if action != "reuse" or not item_id:
            continue
        if not shape:
            # non-strict: a reuse decision without a shape is a warning
            warns.append(f"slide {rid!r}: missing content_shape (required for T1 selection-lock)")
            continue
        if shape not in SHAPE_TYPE_MAP:
            errs.append(f"slide {rid!r}: unknown content_shape {shape!r} "
                        f"(allowed: {', '.join(sorted(SHAPE_TYPE_MAP))})")
            continue
        allowed = SHAPE_TYPE_MAP[shape]
        tokens = reg_tokens.get(item_id, set())
        if not (allowed & tokens):
            errs.append(
                f"slide {rid!r}: content_shape {shape!r} requires one of {sorted(allowed)}, "
                f"but chosen item {item_id!r} has intent/tags {sorted(tokens) or '[]'}"
            )
    return errs, warns


def _validate_slide_entry(slide: dict, idx: int, errors: list[str], warnings: list[str]) -> list[dict]:
    checks: list[dict] = []
    prefix = f"slides[{idx}]"
    dec = slide.get("decision") or {}
    missing_dec = {"action", "item_id", "score", "reason"} - set(dec)
    action = dec.get("action", "")
    action_ok = action in VALID_ACTIONS
    if missing_dec or not action_ok:
        errors.append(f"{prefix} decision: missing={sorted(missing_dec)}, action={action!r}")
    cands = slide.get("candidates")
    if not isinstance(cands, list) or not cands:
        errors.append(f"{prefix}: missing or empty candidates")
        return checks
    for j, cand in enumerate(cands):
        if not isinstance(cand, dict):
            continue
        crit = cand.get("criteria") or {}
        miss = REQUIRED_CRITERIA - set(crit)
        if miss:
            errors.append(f"{prefix}.candidates[{j}] criteria missing: {', '.join(sorted(miss))}")
            break
    item_id = dec.get("item_id")
    if action == "reuse" and not item_id:
        errors.append(f"{prefix}: action='reuse' but item_id is null")
    # Band correctness (confidence bar / explicit-only custom-local) is enforced
    # against the scored candidates in _validate_decision_band.
    _validate_decision_band(slide, prefix, errors)
    return checks


def _validate_batch(rep: dict, checks: list[dict], errors: list[str], warnings: list[str], fail) -> None:
    missing = {"generated_at", "slides"} - set(rep)
    ok = not missing
    checks.append(_chk("schema", ok, "Batch schema valid" if ok else f"Missing: {', '.join(sorted(missing))}"))
    if not ok:
        fail(f"Batch schema missing: {', '.join(sorted(missing))}")

    slides = rep.get("slides", [])
    if not isinstance(slides, list) or not slides:
        fail("Batch report has no slides")
        checks.append(_chk("slides_array", False, "Missing or empty slides array"))
        return
    checks.append(_chk("slides_array", True, f"{len(slides)} slide(s)"))

    slide_errors: list[str] = []
    slide_warnings: list[str] = []
    for i, slide in enumerate(slides):
        if not isinstance(slide, dict):
            slide_errors.append(f"slides[{i}] is not an object")
            continue
        if "request_id" not in slide:
            slide_errors.append(f"slides[{i}] missing request_id")
        _validate_slide_entry(slide, i, slide_errors, slide_warnings)

    ok = not slide_errors
    checks.append(_chk("slide_entries", ok, f"All {len(slides)} entries valid" if ok else f"{len(slide_errors)} error(s)"))
    if not ok:
        for e in slide_errors:
            fail(e)
    warnings.extend(slide_warnings)


def _validate_single(rep: dict, checks: list[dict], errors: list[str], warnings: list[str], fail) -> None:
    missing = {"request_id", "generated_at", "decision", "candidates"} - set(rep)
    ok = not missing
    checks.append(_chk("schema", ok, "All top-level keys present" if ok else f"Missing: {', '.join(sorted(missing))}"))
    if not ok:
        fail(f"Schema missing top-level keys: {', '.join(sorted(missing))}")

    dec = rep.get("decision") or {}
    missing_dec = {"action", "item_id", "score", "reason"} - set(dec)
    action = dec.get("action", "")
    action_ok = action in VALID_ACTIONS
    ok = not missing_dec and action_ok
    detail = "Decision schema valid" if ok else "; ".join(
        ([f"missing: {', '.join(sorted(missing_dec))}"] if missing_dec else [])
        + ([f"invalid action: {action!r}"] if not action_ok else [])
    )
    checks.append(_chk("decision_schema", ok, detail))
    if not ok:
        fail(f"Decision: {detail}")

    cands = rep.get("candidates")
    ok = isinstance(cands, list) and len(cands) > 0
    checks.append(_chk("candidates_array", ok, f"{len(cands)} candidate(s)" if ok else "Missing or empty candidates array"))
    if not ok:
        fail("Candidates: missing or empty array")
        cands = []

    crit_errors: list[str] = []
    for i, cand in enumerate(cands):
        if not isinstance(cand, dict):
            crit_errors.append(f"Candidate[{i}] is not an object")
            continue
        for key in ("item_id", "eligible", "score", "criteria"):
            if key not in cand:
                crit_errors.append(f"Candidate[{i}] missing '{key}'")
        crit = cand.get("criteria") or {}
        miss = REQUIRED_CRITERIA - set(crit)
        if miss:
            crit_errors.append(f"Candidate[{i}] criteria missing: {', '.join(sorted(miss))}")
    ok = not crit_errors
    checks.append(_chk("criteria_sub_scores", ok, "All criteria keys present" if ok else "; ".join(crit_errors[:3])))
    if not ok:
        errors.extend(crit_errors)

    # Equal scores across candidates are legitimate (two items can be equally
    # relevant, or all blocked items score 0.0). The only implausible case is
    # eligible items that all scored zero.
    scores = [c.get("score") for c in cands if isinstance(c, dict) and "score" in c]
    eligible_any = any(c.get("eligible") for c in cands if isinstance(c, dict))
    all_zero = bool(scores) and all(s == 0 for s in scores)
    plaus_ok = not (eligible_any and all_zero)
    detail = "Scores are plausible" if plaus_ok else "All scores are 0 despite eligible items"
    checks.append(_chk("score_plausibility", plaus_ok, detail))
    if not plaus_ok:
        fail(detail)

    item_id = dec.get("item_id")
    adopt_ok = not (action == "reuse" and not item_id)
    checks.append(_chk("adoption_compliance", adopt_ok,
        "Adoption rules satisfied" if adopt_ok else f"action={action!r} but item_id is null"))
    if not adopt_ok:
        fail(f"Adoption: action='reuse' requires non-null item_id")
    _validate_decision_band(rep, "report", errors)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--selection-report", required=True)
    parser.add_argument("--visual-requests", default=None,
                        help="visual-requests.json — required to run the T1 content_shape lock.")
    parser.add_argument("--registry", default=str(SYSTEM_ROOT / "registries/visual-library.json"),
                        help="Full registry (default). Must carry intent/tags for shape-lock.")
    parser.add_argument("--strict-shape", action="store_true",
                        help="Promote a missing content_shape from WARN to a hard FAIL (T1 rollout).")
    args = parser.parse_args()

    report_path = Path(args.selection_report).resolve()
    rep = load_json(report_path)
    checks: list[dict] = []
    errors: list[str] = []
    warnings: list[str] = []

    def fail(msg: str) -> None:
        errors.append(msg)

    is_batch = "slides" in rep and isinstance(rep.get("slides"), list)

    if is_batch:
        _validate_batch(rep, checks, errors, warnings, fail)
    else:
        _validate_single(rep, checks, errors, warnings, fail)

    checks.append(_validate_report_fields(rep, is_batch, errors))

    # Provenance (HARD — both modes). The scorer always stamps generated_by;
    # a report that lacks it or carries any other value was not produced by the
    # scorer and is rejected. This is what backs the "NO hand-written selection
    # reports" prohibition — it must be an error, not a warning.
    generated_by = rep.get("generated_by")
    prov_ok = generated_by == "score_visual_items.py"
    checks.append(_chk("provenance", prov_ok,
        "generated_by is score_visual_items.py" if prov_ok else f"generated_by is {generated_by!r}, expected 'score_visual_items.py'"))
    if not prov_ok:
        fail(f"generated_by is {generated_by!r}, expected 'score_visual_items.py' (report not produced by the scorer)")

    # T1 selection-lock: chosen component's intent/tags must match content_shape.
    # Needs both the registry (for the item's tokens) and visual-requests (for
    # the per-slide content_shape).
    if args.visual_requests:
        try:
            reg_tokens = _registry_tokens(load_json(args.registry))
            shapes = _content_shapes(load_json(args.visual_requests))
            s_errs, s_warns = _validate_shape_lock(rep, is_batch, shapes, reg_tokens, args.strict_shape)
            ok = not s_errs
            checks.append(_chk("shape_lock", ok,
                "content_shape <-> component type consistent" if ok else f"{len(s_errs)} shape mismatch(es)"))
            errors.extend(s_errs)
            warnings.extend(s_warns)
        except Exception as exc:
            warnings.append(f"shape-lock skipped: {exc}")

    # Cross-check with visual-requests (optional)
    if args.visual_requests:
        vreqs = load_json(args.visual_requests)
        if is_batch:
            vreq_ids = {s.get("request_id") for s in vreqs.get("slides", []) if isinstance(s, dict)}
            rep_ids = {s.get("request_id") for s in rep.get("slides", []) if isinstance(s, dict)}
            missing_ids = vreq_ids - rep_ids
            ok = not missing_ids
            checks.append(_chk("request_id_match", ok,
                f"All {len(rep_ids)} request IDs matched" if ok else f"Missing: {', '.join(sorted(missing_ids))}"))
            if not ok:
                fail(f"Cross-check: {len(missing_ids)} request ID(s) from visual-requests not scored")
        else:
            rid = rep.get("request_id")
            req_ids = {r.get("request_id") for r in (vreqs if isinstance(vreqs, list) else vreqs.get("requests", vreqs.get("slides", []))) if isinstance(r, dict)}
            ok = rid in req_ids
            checks.append(_chk("request_id_match", ok,
                f"request_id {rid!r} found" if ok else f"request_id {rid!r} not in visual-requests"))
            if not ok:
                fail(f"Cross-check: request_id {rid!r} not found in visual-requests")

    valid = not errors
    result = {"valid": valid, "checked_at": now_iso(), "report_path": str(report_path),
              "checks": checks, "errors": errors, "warnings": warnings}
    write_json(report_path.parent.parent / "analysis" / "selection-validation.json", result)

    status = "PASS" if valid else "FAIL"
    print(f"validate_selection_report: {status}{f' ({len(warnings)} warning(s))' if warnings else ''} — {report_path.name}")
    for e in errors:
        print(f"  ERROR: {e}")
    for w in warnings:
        print(f"  WARN: {w}")
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
